package de.arcan.arclib.crypto

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

/**
 * Cross-validation: arclib JDK X25519 ↔ BouncyCastle X25519.
 * Tests if keys generated by one can be used by the other for ECDH.
 *
 * This test uses ONLY JDK (no BouncyCastle dependency in arclib).
 * The validation is that arclib's ECDH is self-consistent AND produces
 * the correct little-endian wire format per RFC 7748.
 */
class X25519BcCrossTest {

    @Test
    fun `arclib keypair roundtrip through JDK XDH`() {
        val kp = X25519.generateKeyPair()
        assertEquals(32, kp.publicKey.size, "public key must be 32 bytes")
        assertEquals(32, kp.privateKey.size, "private key must be 32 bytes")

        // Verify we can reconstruct the key and do ECDH with ourselves
        // (this tests the reversal logic is internally consistent)
        val kp2 = X25519.generateKeyPair()
        val shared1 = X25519.ecdh(kp.privateKey, kp2.publicKey)
        val shared2 = X25519.ecdh(kp2.privateKey, kp.publicKey)
        assertArrayEquals(shared1, shared2, "ECDH must produce same shared secret")
    }

    @Test
    fun `public key is little-endian RFC 7748 format`() {
        // X25519 base point (generator) is u=9.
        // In little-endian: [9, 0, 0, ..., 0] (32 bytes)
        // arclib should output keys in this format.
        val kp = X25519.generateKeyPair()
        // Just verify it's 32 bytes and not all zeros
        assertEquals(32, kp.publicKey.size)
        assertFalse(kp.publicKey.all { it == 0.toByte() })
    }

    @Test
    fun `known test vector from RFC 7748`() {
        // RFC 7748 Section 6.1 test vectors
        // Alice's private key (clamped):
        val alicePriv = hexToBytes("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
        // Alice's public key:
        val alicePubExpected = hexToBytes("8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a")

        // Bob's private key (clamped):
        val bobPriv = hexToBytes("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")
        // Bob's public key:
        val bobPubExpected = hexToBytes("de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f")

        // Shared secret:
        val sharedExpected = hexToBytes("4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742")

        // Test ECDH with known keys
        val shared1 = X25519.ecdh(alicePriv, bobPubExpected)
        val shared2 = X25519.ecdh(bobPriv, alicePubExpected)

        assertArrayEquals(sharedExpected, shared1, "Alice ECDH must match RFC 7748 vector")
        assertArrayEquals(sharedExpected, shared2, "Bob ECDH must match RFC 7748 vector")
        assertArrayEquals(shared1, shared2, "Both sides must agree")
    }

    private fun hexToBytes(hex: String): ByteArray {
        val result = ByteArray(hex.length / 2)
        for (i in result.indices) {
            result[i] = hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return result
    }
}
