// MyClerk opcode catalog (canonical reference in arclib; apps copy locally, see cmd/opcode-verify).
// Migrated MyClerk orchestration operation codes (category 0x12).

package protocol

// Orchestration operations (category 0x12).
const (
	OpOrchestrationCreate     OpCode = 0x1200 // Create orchestration
	OpOrchestrationGet        OpCode = 0x1201 // Get orchestration
	OpOrchestrationUpdate     OpCode = 0x1202 // Update orchestration
	OpOrchestrationDelete     OpCode = 0x1203 // Delete orchestration
	OpOrchestrationList       OpCode = 0x1204 // List orchestrations
	OpOrchestrationStats      OpCode = 0x1205 // Get orchestration stats
	OpOrchestrationStart      OpCode = 0x1206 // Start planning
	OpOrchestrationActivate   OpCode = 0x1207 // Activate orchestration
	OpOrchestrationComplete   OpCode = 0x1208 // Complete orchestration
	OpOrchestrationCancel     OpCode = 0x1209 // Cancel orchestration
	OpOrchTaskCreate          OpCode = 0x1210 // Create task
	OpOrchTaskGet             OpCode = 0x1211 // Get task
	OpOrchTaskUpdate          OpCode = 0x1212 // Update task
	OpOrchTaskDelete          OpCode = 0x1213 // Delete task
	OpOrchTaskList            OpCode = 0x1214 // List tasks
	OpOrchTaskAssign          OpCode = 0x1215 // Assign task
	OpOrchTaskComplete        OpCode = 0x1216 // Complete task
	OpOrchTaskSkip            OpCode = 0x1217 // Skip task
	OpBudgetCreate            OpCode = 0x1220 // Create budget
	OpBudgetGet               OpCode = 0x1221 // Get budget
	OpBudgetUpdate            OpCode = 0x1222 // Update budget
	OpBudgetDelete            OpCode = 0x1223 // Delete budget
	OpBudgetCategoryCreate    OpCode = 0x1230 // Create category
	OpBudgetCategoryGet       OpCode = 0x1231 // Get category
	OpBudgetCategoryUpdate    OpCode = 0x1232 // Update category
	OpBudgetCategoryDelete    OpCode = 0x1233 // Delete category
	OpBudgetCategoryList      OpCode = 0x1234 // List categories
	OpExpenseCreate           OpCode = 0x1240 // Add expense
	OpExpenseGet              OpCode = 0x1241 // Get expense
	OpExpenseUpdate           OpCode = 0x1242 // Update expense
	OpExpenseDelete           OpCode = 0x1243 // Delete expense
	OpExpenseList             OpCode = 0x1244 // List expenses
	OpMilestoneCreate         OpCode = 0x1250 // Create milestone
	OpMilestoneGet            OpCode = 0x1251 // Get milestone
	OpMilestoneUpdate         OpCode = 0x1252 // Update milestone
	OpMilestoneDelete         OpCode = 0x1253 // Delete milestone
	OpMilestoneList           OpCode = 0x1254 // List milestones
	OpMilestoneComplete       OpCode = 0x1255 // Complete milestone
	OpMilestoneSkip           OpCode = 0x1256 // Skip milestone
	OpContributorAdd          OpCode = 0x1260 // Add contributor
	OpContributorUpdate       OpCode = 0x1261 // Update contributor
	OpContributorRemove       OpCode = 0x1262 // Remove contributor
	OpContributorList         OpCode = 0x1263 // List contributors
	OpNotificationCreate      OpCode = 0x1270 // Create/send notification
	OpNotificationGet         OpCode = 0x1271 // Get notification by ID
	OpNotificationList        OpCode = 0x1272 // List notifications for user
	OpNotificationMarkRead    OpCode = 0x1273 // Mark notification as read
	OpNotificationMarkAllRead OpCode = 0x1274 // Mark all notifications as read
	OpNotificationDelete      OpCode = 0x1275 // Delete notification
	OpNotificationDeleteAll   OpCode = 0x1276 // Delete all notifications for user
	OpNotificationCount       OpCode = 0x1277 // Get unread count
	OpNotificationPrefsGet    OpCode = 0x1280 // Get user preferences
	OpNotificationPrefsUpdate OpCode = 0x1281 // Update user preferences
	OpNotificationChannelTest OpCode = 0x1282 // Test notification channel
	OpNotificationSubscribe   OpCode = 0x1283 // Subscribe to push notifications
	OpNotificationUnsubscribe OpCode = 0x1284 // Unsubscribe from push
	OpNotificationSend        OpCode = 0x1288 // Admin: send to specific user
	OpNotificationBroadcast   OpCode = 0x1289 // Admin: broadcast to family/all
	OpFinAccountCreate        OpCode = 0x1290 // Create bank account
	OpFinAccountGet           OpCode = 0x1291 // Get bank account
	OpFinAccountUpdate        OpCode = 0x1292 // Update bank account
	OpFinAccountDelete        OpCode = 0x1293 // Delete bank account
	OpFinAccountList          OpCode = 0x1294 // List bank accounts
	OpFinAccountSync          OpCode = 0x1295 // Update sync status
	OpFinTxnImport            OpCode = 0x1298 // Import transactions
	OpFinTxnGet               OpCode = 0x1299 // Get transaction
	OpFinTxnUpdate            OpCode = 0x129A // Update transaction
	OpFinTxnDelete            OpCode = 0x129B // Delete transaction
	OpFinTxnList              OpCode = 0x129C // List transactions
	OpFinTxnCategorize        OpCode = 0x129D // Categorize transaction
	OpFinTxnStats             OpCode = 0x129E // Transaction statistics
	OpFinTxnSearch            OpCode = 0x129F // Search transactions
	OpFinCategoryCreate       OpCode = 0x12A1 // Create category
	OpFinCategoryGet          OpCode = 0x12A2 // Get category
	OpFinCategoryUpdate       OpCode = 0x12A3 // Update category
	OpFinCategoryDelete       OpCode = 0x12A4 // Delete category
	OpFinCategoryList         OpCode = 0x12A5 // List categories
	OpFinCategorySubs         OpCode = 0x12A6 // List subcategories
	OpFinBudgetCreate         OpCode = 0x12A8 // Create budget
	OpFinBudgetGet            OpCode = 0x12A9 // Get budget
	OpFinBudgetUpdate         OpCode = 0x12AA // Update budget
	OpFinBudgetDelete         OpCode = 0x12AB // Delete budget
	OpFinBudgetList           OpCode = 0x12AC // List budgets
	OpFinBudgetStatus         OpCode = 0x12AD // Get budget status
	OpFinBudgetSpend          OpCode = 0x12AE // Record spending
	OpFinAllowanceCreate      OpCode = 0x12B2 // Create allowance account
	OpFinAllowanceGet         OpCode = 0x12B3 // Get allowance account
	OpFinAllowanceUpdate      OpCode = 0x12B4 // Update allowance account
	OpFinAllowanceDelete      OpCode = 0x12B5 // Delete allowance account
	OpFinAllowanceList        OpCode = 0x12B6 // List allowance accounts
	OpFinAllowanceTxnAdd      OpCode = 0x12B7 // Add allowance transaction
	OpFinAllowanceTxnList     OpCode = 0x12B8 // List allowance transactions
	OpFinAllowanceApprove     OpCode = 0x12B9 // Approve pending transaction
	OpFinGoalCreate           OpCode = 0x12BE // Create savings goal
	OpFinGoalGet              OpCode = 0x12BF // Get savings goal
	OpFinGoalUpdate           OpCode = 0x12C0 // Update savings goal
	OpFinGoalDelete           OpCode = 0x12C1 // Delete savings goal
	OpFinGoalList             OpCode = 0x12C2 // List savings goals
	OpFinGoalContribute       OpCode = 0x12C3 // Contribute to savings goal
)
