// MyClerk opcode catalog (canonical reference in arclib; apps copy locally, see cmd/opcode-verify).
// Migrated MyClerk auth operation codes (category 0x01).

package protocol

// Auth operations (category 0x01).
const (
	OpAuthChallenge       OpCode = 0x0100 // Request auth challenge
	OpAuthResponse        OpCode = 0x0101 // Respond to challenge
	OpAuthSuccess         OpCode = 0x0102 // Authentication succeeded
	OpAuthFailed          OpCode = 0x0103 // Authentication failed
	OpAuthRefresh         OpCode = 0x0104 // Refresh session
	OpAuthLogout          OpCode = 0x0105 // End session
	OpAuthMFARequired     OpCode = 0x0106 // MFA step required
	OpAuthMFAVerify       OpCode = 0x0107 // Verify MFA code
	OpSSOInitiate         OpCode = 0x0108 // Initiate SSO login
	OpSSORedirect         OpCode = 0x0109 // Return auth redirect URL
	OpSSOComplete         OpCode = 0x010A // Complete SSO (one-time token)
	OpSSOFailed           OpCode = 0x010B // SSO login failed
	OpSSOProviderList     OpCode = 0x010C // List SSO providers for tenant
	OpSSOProviderGet      OpCode = 0x010D // Get provider details
	OpSSOProviderCreate   OpCode = 0x010E // Create SSO provider (admin)
	OpSSOProviderUpdate   OpCode = 0x010F // Update SSO provider (admin)
	OpSSOProviderDelete   OpCode = 0x0110 // Delete SSO provider (admin)
	OpMFAPolicyGet        OpCode = 0x0111 // Get MFA policy
	OpMFAPolicyUpdate     OpCode = 0x0112 // Update MFA policy (admin)
	OpMFAEnrollInit       OpCode = 0x0113 // Start TOTP enrollment
	OpMFAEnrollConfirm    OpCode = 0x0114 // Confirm TOTP enrollment
	OpMFABackupGen        OpCode = 0x0115 // Generate backup codes
	OpSessionPolicyGet    OpCode = 0x0116 // Get session policy
	OpSessionPolicySet    OpCode = 0x0117 // Update session policy (admin)
	OpSSOIdentityList     OpCode = 0x0118 // List user's SSO identities
	OpSSOIdentityUnlink   OpCode = 0x0119 // Unlink SSO identity
	OpSCIMTokenCreate     OpCode = 0x011A // Create SCIM token
	OpSCIMTokenList       OpCode = 0x011B // List SCIM tokens
	OpSCIMTokenRevoke     OpCode = 0x011C // Revoke SCIM token
	OpLDAPSyncTrigger     OpCode = 0x011D // Trigger LDAP sync
	OpLDAPSyncStatus      OpCode = 0x011E // Get LDAP sync status
	OpGroupMappingList    OpCode = 0x011F // List group-role mappings
	OpSessionCreate       OpCode = 0x0120 // Create new session
	OpSessionDestroy      OpCode = 0x0121 // Destroy session
	OpSessionList         OpCode = 0x0122 // List active sessions
	OpSessionRevokeOne    OpCode = 0x0123 // Revoke specific session
	OpSessionRevokeAll    OpCode = 0x0124 // Revoke all sessions
	OpDeviceRegister      OpCode = 0x0130 // Register new device
	OpDeviceVerify        OpCode = 0x0131 // Verify device
	OpDeviceUnregister    OpCode = 0x0132 // Unregister device
	OpDeviceTrust         OpCode = 0x0133 // Trust device
	OpDeviceUntrust       OpCode = 0x0134 // Untrust device
	OpBackupCodesGen      OpCode = 0x0140 // Generate backup codes
	OpBackupCodesVerify   OpCode = 0x0141 // Verify backup code
	OpMessageSend         OpCode = 0x0150 // Send message
	OpMessageReceive      OpCode = 0x0151 // Receive message
	OpMessageGet          OpCode = 0x0152 // Get message
	OpMessageEdit         OpCode = 0x0153 // Edit message
	OpMessageDelete       OpCode = 0x0154 // Delete message
	OpMessageReact        OpCode = 0x0155 // Add reaction
	OpMessageUnreact      OpCode = 0x0156 // Remove reaction
	OpMessagePin          OpCode = 0x0157 // Pin message
	OpMessageUnpin        OpCode = 0x0158 // Unpin message
	OpMessageForward      OpCode = 0x0159 // Forward message
	OpMessageReply        OpCode = 0x015A // Reply to message
	OpMessageThread       OpCode = 0x015B // Start thread
	OpMessageRead         OpCode = 0x0160 // Mark as read
	OpMessageReadReceipt  OpCode = 0x0161 // Read receipt
	OpTypingStart         OpCode = 0x0170 // Typing indicator start
	OpTypingStop          OpCode = 0x0171 // Typing indicator stop
	OpMessageSearch       OpCode = 0x0180 // Search messages
	OpMessageHistory      OpCode = 0x0181 // Get history
	OpMessageSync         OpCode = 0x0182 // Sync messages
	OpUserCreate          OpCode = 0x0190 // Create user
	OpUserGet             OpCode = 0x0191 // Get user info
	OpUserUpdate          OpCode = 0x0192 // Update user
	OpUserDelete          OpCode = 0x0193 // Delete user
	OpUserList            OpCode = 0x0194 // List users
	OpUserSearch          OpCode = 0x0195 // Search users
	OpUserBlock           OpCode = 0x01A0 // Block user
	OpUserUnblock         OpCode = 0x01A1 // Unblock user
	OpUserMute            OpCode = 0x01A2 // Mute user
	OpUserUnmute          OpCode = 0x01A3 // Unmute user
	OpProfileGet          OpCode = 0x01B0 // Get profile
	OpProfileUpdate       OpCode = 0x01B1 // Update profile
	OpAvatarSet           OpCode = 0x01B2 // Set avatar
	OpAvatarGet           OpCode = 0x01B3 // Get avatar
	OpPreferencesGet      OpCode = 0x01C0 // Get preferences
	OpPreferencesSet      OpCode = 0x01C1 // Set preferences
	OpPasswordChange      OpCode = 0x01D0 // Change password
	OpPasswordReset       OpCode = 0x01D1 // Reset password
	OpEmailChange         OpCode = 0x01D2 // Change email
	OpEmailVerify         OpCode = 0x01D3 // Verify email
	OpWebAuthnRegBegin    OpCode = 0x01D4 // Begin passkey registration (returns challenge)
	OpWebAuthnRegComplete OpCode = 0x01D5 // Complete passkey registration (stores credential)
	OpWebAuthnLoginBegin  OpCode = 0x01D6 // Begin passkey login (returns challenge)
	OpWebAuthnLoginDone   OpCode = 0x01D7 // Complete passkey login (verifies assertion)
	OpWebAuthnList        OpCode = 0x01D8 // List user's registered passkeys
	OpTOTPEnable          OpCode = 0x01E0 // Enable TOTP
	OpTOTPDisable         OpCode = 0x01E1 // Disable TOTP
	OpTOTPVerify          OpCode = 0x01E2 // Verify TOTP
)
