// MyClerk opcode catalog (canonical reference in arclib; apps copy locally, see cmd/opcode-verify).
// Migrated MyClerk call operation codes (category 0x0B).

package protocol

// Call operations (category 0x0B).
const (
	OpCallInitiate           OpCode = 0x0B00 // Initiate call
	OpCallRing               OpCode = 0x0B01 // Ring notification
	OpCallAnswer             OpCode = 0x0B02 // Answer call
	OpCallReject             OpCode = 0x0B03 // Reject call
	OpCallEnd                OpCode = 0x0B04 // End call
	OpCallHold               OpCode = 0x0B05 // Hold call
	OpCallResume             OpCode = 0x0B06 // Resume call
	OpCallTransfer           OpCode = 0x0B07 // Transfer call
	OpCallMute               OpCode = 0x0B10 // Mute microphone
	OpCallUnmute             OpCode = 0x0B11 // Unmute microphone
	OpCallVideoOn            OpCode = 0x0B12 // Enable video
	OpCallVideoOff           OpCode = 0x0B13 // Disable video
	OpCallShare              OpCode = 0x0B14 // Screen share
	OpCallOffer              OpCode = 0x0B20 // WebRTC offer
	OpCallAnswer2            OpCode = 0x0B21 // WebRTC answer
	OpCallICE                OpCode = 0x0B22 // ICE candidate
	OpVoicemailList          OpCode = 0x0B30 // List voicemails
	OpVoicemailGet           OpCode = 0x0B31 // Get voicemail
	OpVoicemailDelete        OpCode = 0x0B32 // Delete voicemail
	OpVoicemailTranscribe    OpCode = 0x0B33 // Transcribe voicemail
	OpVoicemailGreeting      OpCode = 0x0B34 // Set/get greeting
	OpVoicemailSettings      OpCode = 0x0B35 // Voicemail settings
	OpScreeningRuleCreate    OpCode = 0x0B40 // Create screening rule
	OpScreeningRuleGet       OpCode = 0x0B41 // Get screening rule
	OpScreeningRuleUpdate    OpCode = 0x0B42 // Update screening rule
	OpScreeningRuleDelete    OpCode = 0x0B43 // Delete screening rule
	OpScreeningRuleList      OpCode = 0x0B44 // List screening rules
	OpScreeningEvent         OpCode = 0x0B45 // Call screening event
	OpScreeningVerdict       OpCode = 0x0B46 // Screening verdict (allow/block/vm)
	OpSMSCreate              OpCode = 0x0B50 // Create outgoing SMS
	OpSMSSend                OpCode = 0x0B51 // Send SMS via gateway
	OpSMSReceive             OpCode = 0x0B52 // Incoming SMS notification
	OpSMSGet                 OpCode = 0x0B53 // Get SMS by ID
	OpSMSList                OpCode = 0x0B54 // List SMS messages
	OpSMSDelete              OpCode = 0x0B55 // Delete SMS
	OpSMSStatus              OpCode = 0x0B56 // Delivery status update
	OpSMSRetry               OpCode = 0x0B57 // Retry failed SMS
	OpSMSQueueStatus         OpCode = 0x0B58 // Get send queue status
	OpSMSContactLookup       OpCode = 0x0B59 // Lookup contact for number
	OpSMSParsed              OpCode = 0x0B60 // Parsed SMS event (after classification)
	OpSMSCategoryUpdate      OpCode = 0x0B61 // Update SMS category
	OpSMSTANReceived         OpCode = 0x0B62 // TAN/OTP received event
	OpSMSTANAnnounce         OpCode = 0x0B63 // Announce TAN to family
	OpSMSTANAcknowledge      OpCode = 0x0B64 // Acknowledge TAN receipt
	OpSMSTANExpired          OpCode = 0x0B65 // TAN expired notification
	OpSMS2FAForward          OpCode = 0x0B66 // Forward 2FA to device
	OpSMSDeliveryParsed      OpCode = 0x0B67 // Parsed delivery notification
	OpSMSBankingParsed       OpCode = 0x0B68 // Parsed banking notification
	OpSMSAlertParsed         OpCode = 0x0B69 // Parsed alert/warning SMS
	OpEmergencyGatewayStatus OpCode = 0x0B70 // Gateway health status
	OpEmergencyInternetDown  OpCode = 0x0B71 // Internet outage detected
	OpEmergencyInternetUp    OpCode = 0x0B72 // Internet restored
	OpEmergencySMSAlert      OpCode = 0x0B73 // Emergency alert via SMS
	OpEmergencySMSCommand    OpCode = 0x0B74 // Emergency command via SMS
	OpEmergencyGeofenceAlert OpCode = 0x0B75 // Geofence breach alert
	OpEmergencyFallbackRoute OpCode = 0x0B76 // Route via SMS fallback
	OpEmergencyHeartbeat     OpCode = 0x0B77 // Heartbeat check
	OpEmergencyBatteryLow    OpCode = 0x0B78 // Low battery alert
	OpEmergencyPowerLost     OpCode = 0x0B79 // Power failure detected
	OpEmergencyPowerRestored OpCode = 0x0B7A // Power restored
	OpTrunkCreate            OpCode = 0x0B80 // Create SIP trunk
	OpTrunkGet               OpCode = 0x0B81 // Get trunk details
	OpTrunkUpdate            OpCode = 0x0B82 // Update trunk config
	OpTrunkDelete            OpCode = 0x0B83 // Delete trunk
	OpTrunkList              OpCode = 0x0B84 // List trunks for family
	OpTrunkHealth            OpCode = 0x0B85 // Get trunk health status
	OpTrunkTemplates         OpCode = 0x0B86 // List provider templates
	OpTrunkRegister          OpCode = 0x0B87 // Force trunk re-registration
	OpRouteTest              OpCode = 0x0B90 // Test routing for a number (dry-run)
	OpRouteEvaluate          OpCode = 0x0B91 // Evaluate outbound route (LCR)
	OpDIDList                OpCode = 0x0B92 // List all DIDs across trunks
	OpDIDLookup              OpCode = 0x0B93 // Look up which trunk handles a DID
	OpLCRStatus              OpCode = 0x0B94 // Get LCR routing table status
	OpLCRRouteAdd            OpCode = 0x0B95 // Add custom LCR route
	OpLCRRouteRemove         OpCode = 0x0B96 // Remove custom LCR route
	OpRoutingStats           OpCode = 0x0B97 // Get routing statistics
	OpConferenceCreate       OpCode = 0x0BA0 // Create a conference room
	OpConferenceJoin         OpCode = 0x0BA1 // Join a conference room
	OpConferenceLeave        OpCode = 0x0BA2 // Leave a conference room
	OpConferenceKick         OpCode = 0x0BA3 // Kick a participant from a conference
	OpConferenceMute         OpCode = 0x0BA4 // Mute a conference participant
	OpConferenceUnmute       OpCode = 0x0BA5 // Unmute a conference participant
	OpConferenceList         OpCode = 0x0BA6 // List active conferences
	OpConferenceInfo         OpCode = 0x0BA7 // Get conference room details
	OpConferenceEnd          OpCode = 0x0BA8 // End a conference room (owner only)
	OpBridgeCreate           OpCode = 0x0BB0 // Create a cross-channel bridge
	OpBridgeGet              OpCode = 0x0BB1 // Get bridge details
	OpBridgeList             OpCode = 0x0BB2 // List active bridges
	OpBridgeClose            OpCode = 0x0BB3 // Close a bridge
	OpBridgeMute             OpCode = 0x0BB4 // Mute a bridge
	OpBridgeUnmute           OpCode = 0x0BB5 // Unmute a bridge
	OpBridgeHold             OpCode = 0x0BB6 // Hold a bridge
	OpBridgeResume           OpCode = 0x0BB7 // Resume a held bridge
	OpBridgeTransfer         OpCode = 0x0BB8 // Transfer a bridge to a new target
	OpBridgeNotify           OpCode = 0x0BB9 // Incoming call notification across channels
	OpSMSChatCreate          OpCode = 0x0BBA // Create an SMS-chat bridge session
	OpSMSChatClose           OpCode = 0x0BBB // Close an SMS-chat bridge session
	OpSMSChatList            OpCode = 0x0BBC // List SMS-chat bridge sessions
	OpIVRMenuCreate          OpCode = 0x0BC0 // Create IVR menu
	OpIVRMenuGet             OpCode = 0x0BC1 // Get IVR menu
	OpIVRMenuUpdate          OpCode = 0x0BC2 // Update IVR menu
	OpIVRMenuDelete          OpCode = 0x0BC3 // Delete IVR menu
	OpIVRMenuList            OpCode = 0x0BC4 // List IVR menus
	OpIVRSessionStart        OpCode = 0x0BC5 // Start IVR session on call
	OpIVRSessionInfo         OpCode = 0x0BC6 // Get IVR session state
	OpIVRSessionEnd          OpCode = 0x0BC7 // End IVR session
	OpIVRDTMFInput           OpCode = 0x0BC8 // DTMF input event
	OpIVROptionAdd           OpCode = 0x0BC9 // Add menu option
	OpIVROptionUpdate        OpCode = 0x0BCA // Update menu option
	OpIVROptionDelete        OpCode = 0x0BCB // Delete menu option
	OpVideoCallCreate        OpCode = 0x0BD0 // Create video call
	OpVideoCallGet           OpCode = 0x0BD1 // Get video call
	OpVideoCallJoin          OpCode = 0x0BD2 // Join video call
	OpVideoCallLeave         OpCode = 0x0BD3 // Leave video call
	OpVideoCallEnd           OpCode = 0x0BD4 // End video call
	OpVideoCallInvite        OpCode = 0x0BD5 // Invite to video call
	OpVideoCallLayout        OpCode = 0x0BD6 // Set video layout
	OpVideoCallRecord        OpCode = 0x0BD7 // Toggle recording
	OpVideoCallStats         OpCode = 0x0BD8 // Get call stats
	OpVideoCallList          OpCode = 0x0BD9 // List scheduled calls
)
