// Code generated from internal/protocol/opcode.go; DO NOT EDIT.
// Migrated MyClerk health operation codes (category 0x14).

package protocol

// Health operations (category 0x14).
const (
	OpHealthRecordCreate       OpCode = 0x1400 // Create health record
	OpHealthRecordGet          OpCode = 0x1401 // Get health record
	OpHealthRecordUpdate       OpCode = 0x1402 // Update health record
	OpHealthRecordDelete       OpCode = 0x1403 // Delete health record
	OpHealthRecordList         OpCode = 0x1404 // List health records
	OpHealthRecordQuery        OpCode = 0x1405 // Query health records by type/range
	OpMedicationCreate         OpCode = 0x1410 // Create medication
	OpMedicationGet            OpCode = 0x1411 // Get medication
	OpMedicationUpdate         OpCode = 0x1412 // Update medication
	OpMedicationDelete         OpCode = 0x1413 // Delete medication
	OpMedicationList           OpCode = 0x1414 // List medications
	OpMedicationRemind         OpCode = 0x1415 // Medication reminder
	OpMedicationConfirm        OpCode = 0x1416 // Confirm medication taken
	OpMedicationSkip           OpCode = 0x1417 // Skip medication dose
	OpFallDetected             OpCode = 0x1420 // Fall detected event
	OpFallFalsePositive        OpCode = 0x1421 // Mark fall as false positive
	OpEmergencyTrigger         OpCode = 0x1422 // Trigger emergency
	OpEmergencyCancel          OpCode = 0x1423 // Cancel emergency
	OpEmergencyContacts        OpCode = 0x1424 // List emergency contacts
	OpEmergencyContactAdd      OpCode = 0x1425 // Add emergency contact
	OpEmergencyContactRemove   OpCode = 0x1426 // Remove emergency contact
	OpEmergencyContactUpdate   OpCode = 0x1427 // Update emergency contact
	OpEmergencyStatus          OpCode = 0x1428 // Get active emergency status
	OpEmergencyLocationUpdate  OpCode = 0x1429 // Update emergency location
	OpEmergencyCallChainConfig OpCode = 0x142A // Get/set call chain configuration
	OpEmergencyCallChainStatus OpCode = 0x142B // Get call chain escalation status
	OpEmergencyAcknowledge     OpCode = 0x142C // Acknowledge emergency
	OpEmergencyResolve         OpCode = 0x142D // Resolve emergency
	OpEmergencyHistory         OpCode = 0x142E // Get emergency event history
	OpEmergencyActions         OpCode = 0x142F // Get emergency event actions
	OpActivityLog              OpCode = 0x1430 // Log activity
	OpActivityGet              OpCode = 0x1431 // Get activity
	OpActivityList             OpCode = 0x1432 // List activities
	OpActivityStats            OpCode = 0x1433 // Get activity statistics
	OpSleepRecord              OpCode = 0x1434 // Record sleep data
	OpSleepGet                 OpCode = 0x1435 // Get sleep record
	OpSleepList                OpCode = 0x1436 // List sleep records
	OpSleepStats               OpCode = 0x1437 // Get sleep statistics
	OpMoodRecord               OpCode = 0x1440 // Record mood entry
	OpMoodGet                  OpCode = 0x1441 // Get mood entry
	OpMoodList                 OpCode = 0x1442 // List mood entries by date range
	OpMoodDelete               OpCode = 0x1443 // Delete mood entry
	OpHealthAlertCreate        OpCode = 0x1448 // Create health alert
	OpHealthAlertList          OpCode = 0x1449 // List alerts for user
	OpHealthAlertUnacked       OpCode = 0x144A // List unacknowledged alerts
	OpHealthAlertAck           OpCode = 0x144B // Acknowledge alert
	OpHealthAlertDelete        OpCode = 0x144C // Delete alert
	OpDrugInteractionCheck     OpCode = 0x1450 // Check interactions for user's medications
	OpDrugInteractionGet       OpCode = 0x1451 // Get interaction by ID
	OpDrugInteractionCreate    OpCode = 0x1452 // Create interaction record
	OpDrugInteractionDelete    OpCode = 0x1453 // Delete interaction record
	OpHealthPrivacyGet         OpCode = 0x1458 // Get privacy settings
	OpHealthPrivacyUpdate      OpCode = 0x1459 // Update privacy settings
	OpAirQualityRecord         OpCode = 0x1460 // Record air quality reading
	OpAirQualityList           OpCode = 0x1461 // List readings by family
	OpAirQualityRoom           OpCode = 0x1462 // Get readings by room
	OpAirQualityLatest         OpCode = 0x1463 // Get latest family reading
	OpTelehealthCreate         OpCode = 0x1468 // Create appointment
	OpTelehealthGet            OpCode = 0x1469 // Get appointment
	OpTelehealthUpcoming       OpCode = 0x146A // List upcoming appointments
	OpTelehealthComplete       OpCode = 0x146B // Complete appointment
	OpTelehealthCancel         OpCode = 0x146C // Cancel appointment
	OpTelehealthDelete         OpCode = 0x146D // Delete appointment
	OpFitnessGoalCreate        OpCode = 0x1470 // Create fitness goal
	OpFitnessGoalGet           OpCode = 0x1471 // Get fitness goal
	OpFitnessGoalActive        OpCode = 0x1472 // List active goals
	OpFitnessGoalProgress      OpCode = 0x1473 // Update goal progress
	OpFitnessGoalDelete        OpCode = 0x1474 // Delete fitness goal
	OpFitnessChallengeCreate   OpCode = 0x1478 // Create challenge
	OpFitnessChallengeGet      OpCode = 0x1479 // Get challenge
	OpFitnessChallengeActive   OpCode = 0x147A // List active challenges
	OpFitnessChallengeFamily   OpCode = 0x147B // List family challenges
	OpFitnessChallengeUpdate   OpCode = 0x147C // Update challenge
	OpFitnessChallengeDelete   OpCode = 0x147D // Delete challenge
	OpFHIRExportBundle         OpCode = 0x147E // Export health data as FHIR R4 Bundle
	OpFHIRResourceTypes        OpCode = 0x147F // List exportable FHIR resource types
	OpNeighborDiscover         OpCode = 0x1480 // Discover neighbors
	OpNeighborConnect          OpCode = 0x1481 // Connect with neighbor
	OpNeighborGet              OpCode = 0x1482 // Get neighbor info
	OpNeighborList             OpCode = 0x1483 // List neighbors
	OpNeighborBlock            OpCode = 0x1484 // Block neighbor
	OpNeighborUnblock          OpCode = 0x1485 // Unblock neighbor
	OpCircleCreate             OpCode = 0x1486 // Create circle
	OpCircleGet                OpCode = 0x1487 // Get circle by ID
	OpCircleList               OpCode = 0x1488 // List family circles
	OpCircleUpdate             OpCode = 0x1489 // Update circle
	OpCircleDelete             OpCode = 0x148A // Delete circle
	OpCircleMemberAdd          OpCode = 0x148B // Add neighbor to circle
	OpCircleMemberRemove       OpCode = 0x148C // Remove neighbor from circle
	OpCircleMemberList         OpCode = 0x148D // List circle members
	OpCircleTrustCheck         OpCode = 0x148E // Check effective trust permission
	OpToolShareOffer           OpCode = 0x1490 // Offer tool for sharing
	OpToolShareGet             OpCode = 0x1491 // Get tool details
	OpToolShareList            OpCode = 0x1492 // List available tools
	OpToolShareRequest         OpCode = 0x1493 // Request to borrow tool
	OpToolShareApprove         OpCode = 0x1494 // Approve borrow request
	OpToolShareReturn          OpCode = 0x1495 // Return borrowed tool
	OpToolShareUpdate          OpCode = 0x1496 // Update tool listing
	OpToolShareRemove          OpCode = 0x1497 // Remove tool from sharing
	OpTrustPresetSeed          OpCode = 0x1498 // Seed built-in presets for family
	OpTrustPresetList          OpCode = 0x1499 // List trust presets for family
	OpTrustPresetGet           OpCode = 0x149A // Get trust preset by ID
	OpTrustPresetCreate        OpCode = 0x149B // Create custom trust preset
	OpTrustPresetUpdate        OpCode = 0x149C // Update custom trust preset
	OpTrustPresetDelete        OpCode = 0x149D // Delete custom trust preset
	OpTrustApply               OpCode = 0x149E // Apply trust preset to neighbor
	OpTrustOverrideSet         OpCode = 0x149F // Set/clear per-feature trust override
	OpCommunityPostCreate      OpCode = 0x14A0 // Create community post
	OpCommunityPostGet         OpCode = 0x14A1 // Get community post
	OpCommunityPostUpdate      OpCode = 0x14A2 // Update community post
	OpCommunityPostDelete      OpCode = 0x14A3 // Delete community post
	OpCommunityPostList        OpCode = 0x14A4 // List community posts
	OpCommunityEventCreate     OpCode = 0x14A5 // Create community event
	OpCommunityEventGet        OpCode = 0x14A6 // Get community event
	OpCommunityEventList       OpCode = 0x14A7 // List community events
	OpCommunityEventJoin       OpCode = 0x14A8 // Join community event
	OpCommunityEventLeave      OpCode = 0x14A9 // Leave community event
	OpSkillOfferCreate         OpCode = 0x14AA // Create skill offer
	OpSkillOfferGet            OpCode = 0x14AB // Get skill offer by ID
	OpSkillOfferList           OpCode = 0x14AC // List skill offers
	OpSkillRequestCreate       OpCode = 0x14AD // Create skill request
	OpSkillRequestList         OpCode = 0x14AE // List skill requests
	OpSkillMatchCreate         OpCode = 0x14AF // Create skill match
	OpHelpRequestCreate        OpCode = 0x14B0 // Create help request
	OpHelpRequestGet           OpCode = 0x14B1 // Get help request
	OpHelpRequestUpdate        OpCode = 0x14B2 // Update help request
	OpHelpRequestDelete        OpCode = 0x14B3 // Delete help request
	OpHelpRequestList          OpCode = 0x14B4 // List help requests
	OpHelpOffer                OpCode = 0x14B5 // Offer help
	OpHelpAccept               OpCode = 0x14B6 // Accept help offer
	OpHelpComplete             OpCode = 0x14B7 // Mark help as complete
	OpCarpoolCreate            OpCode = 0x14C0 // Create carpool offer
	OpCarpoolGet               OpCode = 0x14C1 // Get carpool details
	OpCarpoolUpdate            OpCode = 0x14C2 // Update carpool
	OpCarpoolDelete            OpCode = 0x14C3 // Delete carpool
	OpCarpoolList              OpCode = 0x14C4 // List carpools
	OpCarpoolSearch            OpCode = 0x14C5 // Search carpools
	OpCarpoolRequest           OpCode = 0x14C6 // Request to join carpool
	OpCarpoolApprove           OpCode = 0x14C7 // Approve carpool request
	OpCarpoolLeave             OpCode = 0x14C8 // Leave carpool
	OpSkillMatchGet            OpCode = 0x14C9 // Get skill match details
	OpSkillMatchUpdate         OpCode = 0x14CA // Accept/decline/complete match
	OpTimeBankBalance          OpCode = 0x14CB // Get time bank balance
	OpTimeBankTransact         OpCode = 0x14CC // Record time exchange
	OpTimeBankHistory          OpCode = 0x14CD // Get transaction history
	OpProviderRecommend        OpCode = 0x14CE // Create provider recommendation
	OpProviderSearch           OpCode = 0x14CF // Search providers + rate
	OpPetCreate                OpCode = 0x14D0 // Create pet profile
	OpPetGet                   OpCode = 0x14D1 // Get pet profile
	OpPetUpdate                OpCode = 0x14D2 // Update pet profile
	OpPetDelete                OpCode = 0x14D3 // Delete pet profile
	OpPetList                  OpCode = 0x14D4 // List family pets
	OpPetArchive               OpCode = 0x14D5 // Archive deceased pet
	OpPetFeedScheduleGet       OpCode = 0x14D8 // Get feeding schedule
	OpPetFeedScheduleSet       OpCode = 0x14D9 // Set feeding schedule
	OpPetFeedLogAdd            OpCode = 0x14DA // Add feeding log entry
	OpPetFeedLogList           OpCode = 0x14DB // List feeding log
	OpPetFeedLogDelete         OpCode = 0x14DC // Delete feeding log entry
	OpPetWalkLogAdd            OpCode = 0x14E0 // Add walk log entry
	OpPetWalkLogList           OpCode = 0x14E1 // List walk log
	OpPetWalkLogDelete         OpCode = 0x14E2 // Delete walk log entry
	OpPetWalkStats             OpCode = 0x14E3 // Get walk statistics
	OpPetVetCreate             OpCode = 0x14E8 // Create vet appointment
	OpPetVetGet                OpCode = 0x14E9 // Get vet appointment
	OpPetVetUpdate             OpCode = 0x14EA // Update vet appointment
	OpPetVetDelete             OpCode = 0x14EB // Delete vet appointment
	OpPetVetList               OpCode = 0x14EC // List vet appointments
	OpPetVaxAdd                OpCode = 0x14ED // Add vaccination record
	OpPetVaxList               OpCode = 0x14EE // List vaccinations
	OpPetVaxDelete             OpCode = 0x14EF // Delete vaccination record
	OpCommunityCreate          OpCode = 0x14F0 // Create community group
	OpCommunityGet             OpCode = 0x14F1 // Get community group by ID
	OpCommunityUpdate          OpCode = 0x14F2 // Update community group
	OpCommunityDelete          OpCode = 0x14F3 // Delete community group
	OpCommunityListAll         OpCode = 0x14F4 // List available communities
	OpCommunityJoin            OpCode = 0x14F5 // Join a community
	OpCommunityLeave           OpCode = 0x14F6 // Leave a community
	OpCommunityMembers         OpCode = 0x14F7 // List community members
	OpModBan                   OpCode = 0x14F8 // Ban member from community
	OpModWarn                  OpCode = 0x14F9 // Warn community member
	OpModMute                  OpCode = 0x14FA // Mute member temporarily
	OpModRemoveContent         OpCode = 0x14FB // Remove content from community
	OpModReverse               OpCode = 0x14FC // Reverse a moderation action
	OpModLog                   OpCode = 0x14FD // Get community moderation log
	OpBlockAdd                 OpCode = 0x14FE // Add family to block list
	OpBlockRemove              OpCode = 0x14FF // Remove family from block list
)
